language: ruby
rvm:
  - 2.2
services:
  - redis-server
install:
  - RAILS_ENV=test bundle install --jobs=3 --retry=3
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - cp config/secrets.yml.default config/secrets.yml
script:
  - bin/rails script/update_hot_posts.rb
  - RAILS_ENV=test bundle exec rake
