app:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    ports:
        - "3000:3000"
    links:
        - redis:redis.local
        - elasticsearch:elasticsearch.local
        - mariadb:mariadb.local
    environment:
        - RAILS_ENV=production
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
        - SENTRY_DSN=${SENTRY_DSN}
        - REDIS_HOST=redis.local
        - REDIS_PORT=6379
        - ELASTICSEARCH_HOST=elasticsearch.local
        - ELASTICSERACH_PORT=9200
        - MARIADB_HOST=mariadb.local
        - MARIADB_PORT=3306

redis:
    image: redis:3.2.4
    ports:
        - "6379"
    volumes:
        - /opt/datadir/redis:/data

elasticsearch:
    image: elasticsearch:5.0.0
    ports:
        - "9200"
        - "9300"
    volumes:
        - /opt/datadir/elasticsearch:/usr/share/elasticsearch/data

mariadb:
    image: mariadb:10.1.18
    environment:
        - MYSQL_ROOT_PASSWORD=badpasswd
        - MYSQL_DATABASE=kata
    ports:
        - "3306"
    volumes:
        - /opt/datadir/mysql:/var/lib/mysql
