app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    ports:
        - "3000:3000"
    links:
        - redis
        - elasticsearch
redis:
    image: redis:3.2.4
    ports:
        - "6379"
elasticsearch:
    image: elasticsearch:5.0.0
    ports:
        - "9200"
        - "9300"
